<?php

namespace App\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository
{
    public function getUsersIn()
    {
        $q = $this
				->createQueryBuilder('u')
				->where('u.state = :in')
				->setParameter('in', true)
				->getQuery()
			;
			
			return $q->getResult();//renvoie objet ou getArrayResult() tableau associatif
    }
    
    
    public function getUsersOut()
    {
        $q = $this
				->createQueryBuilder('u')
				->where('u.state = :out')
				->setParameter('out', false)
				->getQuery()
			;
			
			return $q->getResult();//renvoie objet ou getArrayResult() tableau associatif
    }
}
