<?php

namespace App\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WarAttackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarAttackRepository extends EntityRepository
{

    public function findWar($id)
    {
        $q = $this
                ->createQueryBuilder('w')
                ->where('w.idGdc = :id')
                ->setParameter('id', $id)
                ->getQuery()
        ;

        return $q->getResult();
    }

}
